### ISSUE TITLE
No Controller

### ISSUE THREAD

**Issue by Bryanmuloni** [jaxnz/flutter_google_places_web#2]
Is there a possibility to add a controller property to the FlutterGooglePlacesWeb and onChanged so that the textfield value is retrieved for use.
Thank you.

**Comment by jaxnz** [comment]
Could you explain the use of the controller? For Addresses that don't come up within Google?

**Comment by Bryanmuloni** [comment]
Sorry @jaxnz I meant TextEditingController to help read value from the TextField and onChanged to help notify of any changes to the TextField. Something related to the normal TextField behavior. Otherwise currently to get the value of the searched location one has to use FlutterGooglePlacesWeb.value in a button yet I only want to use one Widget (FlutterGooglePlacesWeb).
I hope my issue is clear now.
