### ISSUE TITLE
Unable to load asset: packages/flutter_google_places/assets/google_white.png

### ISSUE THREAD

**Issue by DevTiago** [jaxnz/flutter_google_places_web#4]
When im trying to fill the searchbox it gives me this error:

![image](https://user-images.githubusercontent.com/41440390/119221877-6899fa80-bae9-11eb-9d85-67d24598ebdc.png)

**Comment by jaxnz** [comment]
Can you give me a `flutter doctor -v`

**Comment by DevTiago** [comment]
[✓] Flutter (Channel master, 2.3.0-13.0.pre.88, on macOS 11.3.1 20E241 darwin-x64, locale en-PT)
    • Flutter version 2.3.0-13.0.pre.88 at /Users/tiago/Code/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2a02037b41 (27 hours ago), 2021-05-21 03:29:02 -0400
    • Engine revision 4f00f9a966
    • Dart version 2.14.0 (build 2.14.0-135.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tiago/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

**Comment by ApofisXII** [comment]
Same issue.

**Comment by jaxnz** [comment]
Fixed in `flutter_google_places_web: ^1.0.0`

**Comment by ankit-deligence3112** [comment]
after adding pakage restart the app
